resolution: 8
annotations:
  split_by_rois:
  - /groups/scicompsoft/home/ackermand/Programming/plasmodesmata_dacapo/preprocessing/annotations/jrc_22ak351-leaf-3mb/annotations_20250818_154715.csv
rois_to_split:
  validation_test:
  - roi_name: '01'
    x: 11824-13716
    y: 11296-10284
    z: 13824-11684
    split_dimension: do_not_split
    type_if_do_not_split: test
  - roi_name: '02'
    x: 9104-8180
    y: 3268-4496
    z: 9900-11744
    split_dimension: do_not_split
    type_if_do_not_split: validation
  - roi_name: '03'
    x: 1612-3564
    y: 14336-13608
    z: 11604-9728
    split_dimension: do_not_split
    type_if_do_not_split: validation
  - roi_name: '04'
    x: 7624-8736
    y: 6528-7612
    z: 14432-15904
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: validation
  - roi_name: '05'
    x: 7280-8152
    y: 12588-13084
    z: 10860-9740
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: test
  - roi_name: '06'
    x: 8824-9396
    y: 8664-9240
    z: 10076-9240
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: validation
  - roi_name: '07'
    x: 8172-9232
    y: 3844-4852
    z: 4368-5600
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: test
  - roi_name: 08
    x: 7252-10152
    y: 8500-9388
    z: 12-1204
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: validation
