resolution: 8
annotations:
  split_by_rois:
  - /groups/scicompsoft/home/ackermand/Programming/plasmodesmata_dacapo/preprocessing/annotations/jrc_22ak351-leaf-3mb/annotations_20250818_154715.csv
  - /groups/scicompsoft/home/ackermand/Programming/plasmodesmata_dacapo/preprocessing/annotations/jrc_22ak351-leaf-3mb/annotations_20250827_133014.csv
  - /groups/scicompsoft/home/ackermand/Programming/plasmodesmata_dacapo/preprocessing/annotations/jrc_22ak351-leaf-3mb/annotations_20250827_133158.csv
rois_to_split:
  validation_test:
  - roi_name: '01'
    x: 11824-13716
    y: 10284-11296
    z: 11684-13824
    split_dimension: do_not_split
    type_if_do_not_split: test
  - roi_name: '02'
    x: 8180-9104
    y: 3268-4496
    z: 9900-11744
    split_dimension: do_not_split
    type_if_do_not_split: validation
  - roi_name: '03'
    x: 1612-3564
    y: 13608-14336
    z: 9728-11604
    split_dimension: do_not_split
    type_if_do_not_split: validation
  - roi_name: '04'
    x: 7624-8736
    y: 6528-7612
    z: 14432-15904
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: validation
  - roi_name: '05'
    x: 7280-8152
    y: 12588-13084
    z: 9740-10860
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: test
  - roi_name: '06'
    x: 8824-9396
    y: 8664-9240
    z: 9240-10076
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: validation
  - roi_name: '07'
    x: 8172-9232
    y: 3844-4852
    z: 4368-5600
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: test
  - roi_name: "08"
    x: 7252-10152
    y: 8500-9388
    z: 12-1204
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: validation
  - roi_name: "09"
    x: 10484-11876
    y: 9388-12288
    z: 14007-16961
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: test
  - roi_name: "10"
    x: 2349-5068
    y: 9472-11947
    z: 2512-4072
    split_dimension: do_not_split
    keep_if_empty: true
    type_if_do_not_split: validation