resolution: 8
annotations:
  split_by_rois:
      - /groups/scicompsoft/home/ackermand/Programming/plasmodesmata_dacapo/preprocessing/annotations/jrc_22ak351-leaf-3rb/annotations_20250121_151258.csv
      - /groups/scicompsoft/home/ackermand/Programming/plasmodesmata_dacapo/preprocessing/annotations/jrc_22ak351-leaf-3rb/annotations_20250121_151302.csv
      - /groups/scicompsoft/home/ackermand/Programming/plasmodesmata_dacapo/preprocessing/annotations/jrc_22ak351-leaf-3rb/annotations_20250121_151307.csv
rois_to_split:
  validation_test:
    - roi_name: "01"
      x: 2242-4795
      y: 9501-11030
      z: 10024-12226
      split_dimension: do_not_split
      type_if_do_not_split: validation
    - roi_name: "02"
      x: 9172-11923
      y: 13461-15583
      z: 9502-11150
      split_dimension: do_not_split
      type_if_do_not_split: test
    - roi_name: "03"
      x: 6397-9051
      y: 9007-11105
      z: 7538-9462
      split_dimension: do_not_split
      type_if_do_not_split: validation
    - roi_name: "04"
      x: 6271-9865
      y: 12975-14929
      z: 4410-5682
      split_dimension: do_not_split
      keep_if_empty: True
      type_if_do_not_split: validation
    - roi_name: "05"
      x: 12449-14029
      y: 5101-7322
      z: 3130-4458
      split_dimension: do_not_split
      keep_if_empty: True
      type_if_do_not_split: test
    - roi_name: "06"
      x: 5089-7569
      y: 4774-6340
      z: 17786-19682
      split_dimension: do_not_split
      keep_if_empty: True
      type_if_do_not_split: validation
    - roi_name: "07"
      x: 8053-10469
      y: 12613-14509
      z: 17422-18786
      split_dimension: do_not_split
      keep_if_empty: True
      type_if_do_not_split: test
    - roi_name: "08"
      x: 11834-13208
      y: 925-2093
      z: 4706-7086
      split_dimension: do_not_split
      keep_if_empty: True
      type_if_do_not_split: validation